# Prometheus configuration for WriteMagic monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'writemagic'
    environment: 'development'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'localhost:9093'

scrape_configs:
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # WriteMagic application metrics
  - job_name: 'writemagic-app'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['writemagic-app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: writemagic-app:8080

  # System metrics (node-exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']

  # Redis metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['localhost:9121']

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']

  # Rust application specific metrics
  - job_name: 'writemagic-rust-core'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['writemagic-app:3000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'rust_.*'
        target_label: component
        replacement: 'core'

  # Mobile app metrics (via proxy)
  - job_name: 'writemagic-mobile'
    metrics_path: '/mobile-metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['writemagic-app:8080']
    metric_relabel_configs:
      - source_labels: [platform]
        target_label: mobile_platform

  # CI/CD pipeline metrics
  - job_name: 'github-actions'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['api.github.com']
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/github-token

# Remote write configuration for long-term storage
remote_write:
  - url: "https://prometheus-remote-write.example.com/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true