# This file contains secret templates - actual values should be injected during deployment
apiVersion: v1
kind: Secret
metadata:
  name: writemagic-secrets
  namespace: writemagic-ENVIRONMENT
  labels:
    app.kubernetes.io/name: writemagic
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: writemagic
type: Opaque
stringData:
  # Database connection (will be populated from AWS Secrets Manager or environment)
  database-url: "postgresql://writemagic_user:PASSWORD@DATABASE_ENDPOINT:5432/writemagic"
  database-host: "DATABASE_ENDPOINT"
  database-port: "5432"
  database-name: "writemagic"
  database-username: "writemagic_user"
  database-password: "DATABASE_PASSWORD"
  
  # Redis connection (will be populated from Terraform outputs)
  redis-url: "redis://REDIS_AUTH_TOKEN@REDIS_ENDPOINT:6379"
  redis-host: "REDIS_ENDPOINT"
  redis-port: "6379"
  redis-auth-token: "REDIS_AUTH_TOKEN"
  
  # JWT and encryption secrets
  jwt-secret: "JWT_SECRET_KEY"
  encryption-key: "ENCRYPTION_SECRET_KEY"
  
  # Session and cookie secrets
  session-secret: "SESSION_SECRET_KEY"
  cookie-secret: "COOKIE_SECRET_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: writemagic-ai-secrets
  namespace: writemagic-ENVIRONMENT
  labels:
    app.kubernetes.io/name: writemagic
    app.kubernetes.io/component: ai-secrets
    app.kubernetes.io/part-of: writemagic
type: Opaque
stringData:
  # AI Provider API Keys (will be injected from GitHub Secrets or AWS Secrets Manager)
  claude-api-key: "CLAUDE_API_KEY"
  openai-api-key: "OPENAI_API_KEY"
  
  # AI Provider Configuration
  claude-model: "claude-3-sonnet-20240229"
  openai-model: "gpt-4-turbo-preview"
  
  # AI Provider Endpoints (for custom deployments)
  claude-endpoint: "https://api.anthropic.com"
  openai-endpoint: "https://api.openai.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: writemagic-monitoring-secrets
  namespace: writemagic-ENVIRONMENT
  labels:
    app.kubernetes.io/name: writemagic
    app.kubernetes.io/component: monitoring-secrets
    app.kubernetes.io/part-of: writemagic
type: Opaque
stringData:
  # Datadog (if enabled)
  datadog-api-key: "DATADOG_API_KEY"
  
  # Slack (for alerting)
  slack-webhook-url: "SLACK_WEBHOOK_URL"
  
  # PagerDuty (for critical alerts)
  pagerduty-integration-key: "PAGERDUTY_INTEGRATION_KEY"
---
# External Secrets Operator integration (optional)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: writemagic-aws-secrets-store
  namespace: writemagic-ENVIRONMENT
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        secretRef:
          accessKeyID:
            name: aws-secrets-manager-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-secrets-manager-credentials
            key: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: writemagic-database-secret
  namespace: writemagic-ENVIRONMENT
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: writemagic-aws-secrets-store
    kind: SecretStore
  target:
    name: writemagic-database-credentials
    creationPolicy: Owner
  data:
  - secretKey: database-url
    remoteRef:
      key: writemagic/ENVIRONMENT/database
      property: connection_url
  - secretKey: database-password
    remoteRef:
      key: writemagic/ENVIRONMENT/database
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: writemagic-ai-keys-secret
  namespace: writemagic-ENVIRONMENT
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: writemagic-aws-secrets-store
    kind: SecretStore
  target:
    name: writemagic-ai-provider-keys
    creationPolicy: Owner
  data:
  - secretKey: claude-api-key
    remoteRef:
      key: writemagic/ENVIRONMENT/ai-providers
      property: claude_api_key
  - secretKey: openai-api-key
    remoteRef:
      key: writemagic/ENVIRONMENT/ai-providers
      property: openai_api_key